In [1]:
# imports
import pandas as pd
import gseapy as gp
bm = gp.Biomart()

In [7]:
#load data
data = pd.read_csv("/home/cvillazon/scripts/samble_data_biomart.csv", header=0, index_col=0)
data

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,-log10(padj),regulation
ENSMUSG00000066170,20.962292,-2.429137,0.627910,-3.868604,0.000109,0.002369,2.625429,Down
ENSMUSG00000041261,1099.442138,-0.464730,0.141985,-3.273093,0.001064,0.015885,1.799026,Down
ENSMUSG00000056429,2163.443904,0.582219,0.138347,4.208410,0.000026,0.000699,3.155444,Up
ENSMUSG00000039873,21.699923,-1.513266,0.479182,-3.158017,0.001588,0.021754,1.662454,Down
ENSMUSG00000046753,65.675872,1.047814,0.275519,3.803054,0.000143,0.002982,2.525446,Up
...,...,...,...,...,...,...,...,...
ENSMUSG00000042246,95.876814,-1.383596,0.296287,-4.669777,0.000003,0.000110,3.957874,Down
ENSMUSG00000022425,960.731936,-0.918194,0.218113,-4.209712,0.000026,0.000698,3.156318,Down
ENSMUSG00000111605,101.383057,-0.983800,0.250860,-3.921705,0.000088,0.001949,2.710109,Down
ENSMUSG00000099997,26.664534,1.487777,0.440447,3.377877,0.000730,0.011804,1.927953,Up
ENSMUSG00000111709,17.975394,2.303870,0.645950,3.566636,0.000362,0.006682,2.175071,Up

In [8]:
queries ={'ensembl_gene_id': list(data.index) } 
results = bm.query(dataset='mmusculus_gene_ensembl',
                   attributes=['ensembl_gene_id', 'external_gene_name', 'entrezgene_id', 'go_id'],
                   filters=queries)

results

         ensembl_gene_id external_gene_name  entrezgene_id       go_id
0     ENSMUSG00000001123             Lgals9          16859  GO:0030246
1     ENSMUSG00000001123             Lgals9          16859  GO:0005634
2     ENSMUSG00000001123             Lgals9          16859  GO:0019899
3     ENSMUSG00000001123             Lgals9          16859  GO:0005737
4     ENSMUSG00000001123             Lgals9          16859  GO:0002376
...                  ...                ...            ...         ...
1650  ENSMUSG00000119520            Gm24265      115490317  GO:0017070
1651  ENSMUSG00000119520            Gm24265      115490317  GO:0000244
1652  ENSMUSG00000119520            Gm24265      115490317  GO:0000353
1653  ENSMUSG00000119520            Gm24265      115490317  GO:0005687
1654  ENSMUSG00000119520            Gm24265      115490317  GO:0046540

[1655 rows x 4 columns]